# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_simulation_cpp <- function(flags, hostPopn, virusPars, day, final_day, input_files, output_files, VERBOSE, scenario, callback) {
    .Call('driftSim_run_simulation_cpp', PACKAGE = 'driftSim', flags, hostPopn, virusPars, day, final_day, input_files, output_files, VERBOSE, scenario, callback)
}

