# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generateStartK <- function(dist) {
    .Call('driftSim_generateStartK', PACKAGE = 'driftSim', dist)
}

generateKSamples <- function(cumSumK, N) {
    .Call('driftSim_generateKSamples', PACKAGE = 'driftSim', cumSumK, N)
}

callFunction <- function(filename, N, f) {
    .Call('driftSim_callFunction', PACKAGE = 'driftSim', filename, N, f)
}

countKs <- function(ks, N) {
    .Call('driftSim_countKs', PACKAGE = 'driftSim', ks, N)
}

run_simulation_cpp <- function(flags, hostPopn, virusPars, deltaVMat, iniKs, day, final_day, input_files, output_files, VERBOSE, scenario, callback) {
    .Call('driftSim_run_simulation_cpp', PACKAGE = 'driftSim', flags, hostPopn, virusPars, deltaVMat, iniKs, day, final_day, input_files, output_files, VERBOSE, scenario, callback)
}

