# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @useDynLib driftSim
generateStartK <- function(dist) {
    .Call('_driftSim_generateStartK', PACKAGE = 'driftSim', dist)
}

#' @export
#' @useDynLib driftSim
generateKSamples <- function(cumSumK, N) {
    .Call('_driftSim_generateKSamples', PACKAGE = 'driftSim', cumSumK, N)
}

#' @export
#' @useDynLib driftSim
callFunction <- function(filename, N, f) {
    .Call('_driftSim_callFunction', PACKAGE = 'driftSim', filename, N, f)
}

#' @export
#' @useDynLib driftSim
countKs <- function(ks, N) {
    .Call('_driftSim_countKs', PACKAGE = 'driftSim', ks, N)
}

#' @export
#' @useDynLib driftSim
run_simulation_cpp <- function(flags, hostPopn, virusPars, deltaVMat, iniKs, day, final_day, input_files, output_files, VERBOSE, scenario, callback) {
    .Call('_driftSim_run_simulation_cpp', PACKAGE = 'driftSim', flags, hostPopn, virusPars, deltaVMat, iniKs, day, final_day, input_files, output_files, VERBOSE, scenario, callback)
}

