// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// run_simulation_cpp
int run_simulation_cpp(Rcpp::IntegerVector flags, Rcpp::NumericVector hostPopn, Rcpp::NumericVector virusPars, Rcpp::NumericMatrix deltaVMatrix, int day, int final_day, std::vector<std::string> input_files, std::vector<std::string> output_files, bool VERBOSE, int scenario, SEXP callback);
RcppExport SEXP driftSim_run_simulation_cpp(SEXP flagsSEXP, SEXP hostPopnSEXP, SEXP virusParsSEXP, SEXP deltaVMatrixSEXP, SEXP daySEXP, SEXP final_daySEXP, SEXP input_filesSEXP, SEXP output_filesSEXP, SEXP VERBOSESEXP, SEXP scenarioSEXP, SEXP callbackSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type flags(flagsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hostPopn(hostPopnSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type virusPars(virusParsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type deltaVMatrix(deltaVMatrixSEXP);
    Rcpp::traits::input_parameter< int >::type day(daySEXP);
    Rcpp::traits::input_parameter< int >::type final_day(final_daySEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type input_files(input_filesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type output_files(output_filesSEXP);
    Rcpp::traits::input_parameter< bool >::type VERBOSE(VERBOSESEXP);
    Rcpp::traits::input_parameter< int >::type scenario(scenarioSEXP);
    Rcpp::traits::input_parameter< SEXP >::type callback(callbackSEXP);
    __result = Rcpp::wrap(run_simulation_cpp(flags, hostPopn, virusPars, deltaVMatrix, day, final_day, input_files, output_files, VERBOSE, scenario, callback));
    return __result;
END_RCPP
}
